# Generated by Django 5.0.9 on 2024-09-12 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_subscription_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("premium", "Premium Perm"),
                    ("basic", "Basic  Perm"),
                    ("free", "Free Perm"),
                ]
            },
        ),
    ]
