# Generated by Django 5.0.9 on 2024-09-12 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("coach", "Coach Perm"),
                    ("premium", "Premium Perm"),
                    ("basic", "Basic  Perm"),
                    ("free", "Free Perm"),
                ]
            },
        ),
    ]
