# Generated by Django 5.1.1 on 2024-09-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("inperson", "In person"), ("virtual", "Virtual")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
